# Section 1
## Linear Algebra

- lista

In [2]:
import numpy as np

### Scalars and Tensors

In [3]:
Scalar = 1

In [4]:
Vector = np.array([1, 2])

In [5]:
Matrix = np.array([ [1, 2], [3, 4] ])

In [6]:
Tensor = np.array([ [ [1, 2], [3, 2] ], [ [1, 7], [5, 4] ] ])

### Matrix Operations

Addition

In [7]:
np.array([[3,8],[4,6]]) + np.array([[4,0],[1,-9]])

array([[ 7,  8],
       [ 5, -3]])

Substraction

In [8]:
np.array([[3,8],[4,6]]) - np.array([[4,0],[1,-9]])

array([[-1,  8],
       [ 3, 15]])

Transpose

In [9]:
np.transpose(np.array([[6,4,24],[1,-9,8]]))

array([[ 6,  1],
       [ 4, -9],
       [24,  8]])

Scalar Multiplication

In [10]:
2 * np.array([[4,0],[1,-9]])

array([[  8,   0],
       [  2, -18]])

Elementwise Multiplication (Haddamard product)

In [11]:
np.array([1,2]) * np.array([3,4])

array([3, 8])

Dot Product

In [12]:
A = np.array([[3,8],[4,6],[10,6]])
B = np.array([[4,0],[1,-9]])
A.dot(B)

array([[ 20, -72],
       [ 22, -54],
       [ 46, -54]])

In [13]:
# Using @ notation
A@B

array([[ 20, -72],
       [ 22, -54],
       [ 46, -54]])